---
- hosts: all
  sudo: yes

  vars_files:
    - vars/main.yml

  roles:
      #- common

      #- ansible
      - docker
      - vagrant
      - denkhaus.virtualbox

      #- desktop
      - { role: phpstorm, phpstorm_version: EAP-143.790 }
     #- test
