---
- name: Sync bats
  git: repo=https://github.com/sstephenson/bats.git dest=/usr/local/src/bats

- name: Install bats
  command:
    /usr/local/src/bats/install.sh /usr/local
    creates=/usr/local/libexec/bats
