---

- name: Update system packages
  apt:
        upgrade=safe
        update_cache=yes
        cache_valid_time=3600

- name: Install common packages
  apt: name={{item}} state=latest
  with_items: common_packages

#- name: Remove apt pip
#  apt: name=python-pip
#       state=absent

- name: Install easy_install pip
  easy_install: name=pip
