---

- name: Update system packages
  apt:
        upgrade=safe
        update_cache=yes
        cache_valid_time=3600

- name: Install common packages
  apt: name={{item}} state=latest
  with_items: common_packages

- name: Install easy_install pip
  easy_install: name=pip

- name: Install pip packages
  pip: name={{ item }} state=latest
  with_items: pip_packages
  tags: [ common, packages ]
