---
# TODO: папку с ключами надо вынести из common в более общее место, возможно, в group_vars
# папка лежит в /files всего дерева

- name: Add ssh public keys to root
  authorized_key:
    user=root
    key="{{ lookup('file', item) }}"
  with_fileglob:
    - ../../../files/public-keys/*

- name: Remove old ssh public keys from root
  authorized_key:
    user=root
    key="{{ lookup('file', item) }}"
    state=absent
  with_fileglob:
    - ../../../files/removed-keys/*
